snc_redis:
    clients:
        default:
            type: phpredis
            alias: default
            dsn: '%env(REDIS_URL)%'
            logging: '%kernel.debug%'
        cache:
            type: phpredis
            alias: cache
            dsn: '%env(REDIS_URL)%'
            logging: '%kernel.debug%'
            options:
                connection_timeout: 10
                read_write_timeout: 30
